# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/661faedb-04a3-4adf-be88-7ac397370b4c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-07ad5a8d-0a43-4fad-8741-f99c2e34ec9e".device = "/dev/disk/by-uuid/07ad5a8d-0a43-4fad-8741-f99c2e34ec9e";

  boot.initrd.luks.devices."sus".device = "/dev/disk/by-uuid/8ae43d47-746c-43b0-8c04-afbbeaac6a10";

  boot.initrd.luks.devices."sus".crypttabExtraOpts = ["fido2-device=auto"];  
  boot.initrd.luks.devices."luks-07ad5a8d-0a43-4fad-8741-f99c2e34ec9e".crypttabExtraOpts = ["fido2-device=auto"];  

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/D582-553D";
      fsType = "vfat";
      options = [
        "defaults"
        "noexec"
        "nodev"
        "nosuid"
      ];
    };

  fileSystems."/home" = 
    { device = "/dev/mapper/sus";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b8be2e9c-cd46-4cae-8ad6-ddfde70b6fdc"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
